### PR TITLE
Fix: Remove error in console

### PR DESCRIPTION
**Pull request by aryamanpuri**
For https://github.com/taskcluster/taskcluster/issues/2263
@helfi92

### CODE REVIEW

**Comment by aryamanpuri** [comment]
@helfi92 Error is of changing _MarkdownProps_ to _Markdownprops_.

Screenshot from 2020-01-16 20-44-09

**Comment by helfi92** [comment]
Do you still see the error after implementing the diff mentioned above? You can test it by running the components styleguide. https://github.com/mozilla-frontend-infra/components/blob/master/README.md#development-and-contributing

**Comment by aryamanpuri** [comment]
Can you explain to me this, why is the error not showing now ?

**Comment by helfi92** [comment]
It's because markdownProps was being fed to the TextField component. markdownProps is not defined in TextField...

```jsx
render() {
  const { classes, rows, markdownProps } = this.props;
  const { onChange, defaultTabIndex, ...props } = this.props;
  
  // ...
    
  <TextField
    name="Write"
    onChange={this.handleValueChange}
    fullWidth
    multiline
    rows={rows}
    // ...props  will have markdownProps which is not defined in TextField
    {...props}
    value={props.value || value}
/>
  }
```

**Comment by helfi92** [comment]
Could you rename the pull-request to follow the convention we use for this repo? https://github.com/mozilla-frontend-infra/components#committing-and-pushing-changes Thanks!

**Comment by aryamanpuri** [comment]
> Could you rename the pull-request to follow the convention we use for this repo? https://github.com/mozilla-frontend-infra/components#committing-and-pushing-changes Thanks!

Done

**Pull request merged**
