### PR TITLE
Change anchor color in Markdown component

### PR DESCRIPTION
**Pull request by aimenbatool**
Color for the anchor is changed in order to fix the issue [#127](https://github.com/taskcluster/taskcluster-web/issues/127) at `taskcluster-web` repo.

### CODE REVIEW

**Comment by aimenbatool** [comment]
Hi @helfi92, Please review this PR and recommend any changes if required. 
Thanks

**Comment by eliperelman** [comment]
What is the default style of the anchors? Currently we set the style to `textDecoration: 'none'`, but I'm wondering if underline was the default.

**Comment by helfi92** [comment]
@aimenbatool Does the error look the same if you remove `textDecoration: 'underline'`?

**Comment by aimenbatool** [comment]
I added `textDecoration: 'underline'` to differentiate error link from the normal text. 
Here is with and without an underline. 

img - 1

img - 2

**Comment by helfi92** [comment]
@aimenbatool We definitely need the link underlined to differentiate between a link and normal text. My question is about whether the underline is still here if you remove line 181 and 183. The reason why we are asking is because we think the underline style will still be applied even when `textDecoration: underline` is removed.

**Comment by aimenbatool** [comment]
@helfi92 No, after removing underline it doesn't apply by default.

**Comment by helfi92** [comment]
@aimenbatool Are you sure? I just tried it out on my machine and the underline seem to be there.

**Comment by aimenbatool** [comment]
@helfi92 sure. 
I commented line 181 & 183 and added a link.
See: 

3mozilla frontend infra components style guide

**Comment by helfi92** [comment]
What is the code you are using to render this error?

**Comment by aimenbatool** [comment]
In the original repo, it is already set to `textDecoration: 'underline'` at time of hover. Without hover, it was set to       `textDecoration: 'none'`,  which is updated to **underline**.  [See here](https://github.com/mozilla-frontend-infra/components/blob/master/src/components/Markdown/index.jsx#L183)

**Comment by aimenbatool** [comment]
> What is the code you are using to render this error?

I'm doing inspect element and making writing an anchor element with text.

**Comment by helfi92** [comment]
My question was how you were rendering a link (e.g., `<ErrorPanel error="what is here?" />`).

Regarding the styling, I was thinking of:

```jsx
'& a, & a code': {
  color: theme.palette.error.contrastText,
},
```

**Comment by aimenbatool** [comment]
This is how I'm producing the error. In the browser. 

screenshot from 2018-10-02 22-48-41

Regarding styling, `underline` was already [there](https://github.com/mozilla-frontend-infra/components/blob/master/src/components/Markdown/index.jsx#L183) for hover. And for the link without hover, it was set to none. 
So, logically after removing it shouldn't underline which is the case in current scenerio.

**Comment by helfi92** [comment]
Do the following:

Click on `VIEW CODE` then edit the code to be:

screen shot 2018-10-02 at 1 56 53 pm

**Comment by helfi92** [comment]
> Regarding styling, underline was already there for hover

Remove it.

> And for the link without hover, it was set to none.

Remove it.

**Comment by aimenbatool** [comment]
@helfi92 Updated. Thanks for the help.

**Pull request merged**
