### PR TITLE
Add branding

### PR DESCRIPTION
**Pull request by helfi92**
The moon (C shaped for "components") with northern light colors.

### CODE REVIEW

**Comment by helfi92** [comment]
https://sketch.cloud/s/Anaby

/cc @eliperelman @armenzg

Feel free to voice your opinion :)

**Comment by armenzg** [comment]
I like it 👍 

The only thing I would throw out there is if:
* We want to use a similar colour scheme as the TaskCluster logo
  * I don't have it handy so I can't compare

**Comment by eliperelman** [comment]
> We want to use a similar colour scheme as the TaskCluster logo

Why?

**Comment by armenzg** [comment]
>> We want to use a similar colour scheme as the TaskCluster logo

> Why?
Perhaps a family of related logos. I'm not tied to the idea.

**Comment by eliperelman** [comment]
Yeah, Taskcluster is not related at all.

**Comment by eliperelman** [comment]
Although we still have this:

logo

**Comment by helfi92** [comment]
Now that Taskcluster has a new logo, https://github.com/mozilla-frontend-infra/components/pull/2#issuecomment-403501338 is not related to Taskcluster anymore 😅
 
Ok, seems like there isn't any contention with the logo. I will go ahead with the merge. Thank you both for your input!

**Pull request merged**
